2023-03-08 17:23:19,171 INFO    MainThread:23883 [wandb_setup.py:_flush():76] Configure stats pid to 23883
2023-03-08 17:23:19,171 INFO    MainThread:23883 [wandb_setup.py:_flush():76] Loading settings from /home/daniel/.config/wandb/settings
2023-03-08 17:23:19,171 INFO    MainThread:23883 [wandb_setup.py:_flush():76] Loading settings from /home/daniel/Repos/Mujoco_Python_Sandbox/value_gradient/wandb/settings
2023-03-08 17:23:19,171 INFO    MainThread:23883 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-03-08 17:23:19,171 INFO    MainThread:23883 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-03-08 17:23:19,171 INFO    MainThread:23883 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'value_gradient/tv_value_synthesis_trajopt_cartpole.py', 'program': 'tv_value_synthesis_trajopt_cartpole.py'}
2023-03-08 17:23:19,171 INFO    MainThread:23883 [wandb_init.py:_log_setup():506] Logging user logs to /home/daniel/Repos/Mujoco_Python_Sandbox/value_gradient/wandb/run-20230308_172319-0qof5q2d/logs/debug.log
2023-03-08 17:23:19,172 INFO    MainThread:23883 [wandb_init.py:_log_setup():507] Logging internal logs to /home/daniel/Repos/Mujoco_Python_Sandbox/value_gradient/wandb/run-20230308_172319-0qof5q2d/logs/debug-internal.log
2023-03-08 17:23:19,172 INFO    MainThread:23883 [wandb_init.py:init():546] calling init triggers
2023-03-08 17:23:19,172 INFO    MainThread:23883 [wandb_init.py:init():553] wandb.init called with sweep_config: {}
config: {}
2023-03-08 17:23:19,172 INFO    MainThread:23883 [wandb_init.py:init():602] starting backend
2023-03-08 17:23:19,172 INFO    MainThread:23883 [wandb_init.py:init():606] setting up manager
2023-03-08 17:23:19,180 INFO    MainThread:23883 [backend.py:_multiprocessing_setup():108] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-03-08 17:23:19,185 INFO    MainThread:23883 [wandb_init.py:init():613] backend started and connected
2023-03-08 17:23:19,192 INFO    MainThread:23883 [wandb_init.py:init():701] updated telemetry
2023-03-08 17:23:19,268 INFO    MainThread:23883 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
2023-03-08 17:23:20,042 INFO    MainThread:23883 [wandb_run.py:_on_init():2131] communicating current version
2023-03-08 17:23:20,173 INFO    MainThread:23883 [wandb_run.py:_on_init():2140] got version response 
2023-03-08 17:23:20,174 INFO    MainThread:23883 [wandb_init.py:init():789] starting run threads in backend
2023-03-08 17:23:25,256 WARNING MsgRouterThr:23883 [router.py:message_loop():77] message_loop has been closed
2023-03-08 17:23:35,197 ERROR   MainThread:23883 [wandb_init.py:init():1171] error
Traceback (most recent call last):
  File "/home/daniel/.local/share/virtualenvs/Mujoco_Python_Sandbox-gNKKWzd6/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1144, in init
    run = wi.init()
  File "/home/daniel/.local/share/virtualenvs/Mujoco_Python_Sandbox-gNKKWzd6/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 801, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/home/daniel/.local/share/virtualenvs/Mujoco_Python_Sandbox-gNKKWzd6/lib/python3.7/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
